version: 0.2

phases:

  install:
    runtime-versions:
      java: openjdk11

    commands:

      # Upgrade AWS CLI to the latest version
      # Install aws-sam-cli
      - pip3 install aws-sam-cli

  build:
    commands:
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
