version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - pip3 install aws-sam-cli
      - apt install -q -y jq
  build:
    commands:
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET --output-template-file sampackaged_raw.yaml
  post_build:
    commands:
      # Getting latest version tag from git
      - APPLICATION_VERSION=$(curl -s  https://api.github.com/repos/BIBSYSDEV/$GIT_REPO/releases/latest | jq -r '.tag_name')
      # Updating metadata.labels in template
      - envsubst < sampackaged_raw.yaml > sampackaged.yaml
      # publishing to SAR
      - sam publish  --semantic-version $APPLICATION_VERSION  --template sampackaged.yaml
artifacts:
  files:
    - sampackaged.yaml
