version: 0.2

env:
  shell: bash
  secrets-manager:
    DOCKER_HUB_USERNAME: bibsdockeraccount:DockerHubUsername
    DOCKER_HUB_SECRET: bibsdockeraccount:DockerHubSecret

phases:

  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto11
    commands:
      # Upgrade AWS CLI to the latest version
      # Install aws-sam-cli
      - pip3 install aws-sam-cli
      - echo "Check docker is running"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    on-failure: ABORT
    commands:
      - echo "pre_build steps for revision ${CODEBUILD_RESOLVED_SOURCE_VERSION}..."
      - env
      - node -v
      - aws --version
      - echo -n "$DOCKER_HUB_SECRET" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - docker pull amazonlinux:latest
      - ./gradlew buildNativeLambda

  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged_raw.yaml

  post_build:
    on-failure: ABORT
    commands:
      - BUILD_TIMESTAMP=$(date '+%s')
      - envsubst '${BUILD_TIMESTAMP}' < packaged_raw.yaml > packaged.yml
      - ls -l

artifacts:
  files:
    - "**/*"
