AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'OPTIONS, GET, PUT, POST'"
      AllowOrigin: "'*'"


Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
  AlmaSruHost:
    Type: String
    Description: Address to Alma-SRU
    Default: '{{resolve:ssm:almaSruHost:2}}'

Resources:

  NvaAlmaSruProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      EndpointConfiguration: Regional
      Models:
        FetchAlmaRecordEventModel:
          type: object
          properties:
            scn:
              type: string
            creatorname:
              type: string


  NvaFetchAlmaRecordFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          ALMA_SRU_HOST: !Ref AlmaSruHost
      Handler: no.unit.nva.alma.FetchAlmaRecordHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        NvaFetchAlmaRecordEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              Authorizer: MyCognitoAuthorizer
            RestApiId: !Ref NvaAlmaSruProxyApi
            Method: get
            Path: /
            RequestParameters:
              - method.request.querystring.scn:
                  Required: true
              - method.request.querystring.creatorname:
                  Required: true


  NvaAlmaSruProxyBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref NvaAlmaSruProxyApi
      Stage: !Ref NvaAlmaSruProxyApi.Stage
