AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sets up lambda, api and base path mapping to fetch most recent publication for an author

Metadata:
  AWS::ServerlessRepo::Application:
    Name: SruLastPublication
    Description: Fetches most recent publication for an author via SRU from a library system
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels: ['${CODEBUILD_RESOLVED_SOURCE_VERSION}', '${GIT_REPO}', '@${BUILD_TIMESTAMP}']

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'OPTIONS, GET'"
      AllowOrigin: "'*'"


Parameters:
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
  AlmaSruHost:
    Type: String
    Description: Address to Alma-SRU

Resources:
  AlmaSruProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}"
      StageName: v1
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        openapi: 3.0.0
        info:
          title: Alma SRU Proxy
          version: '1.0'
        paths:
          /alma:
            get:
              summary:  Get Alma record given by mms_id and optional institution
              description:  gets the Alma record by mms_id
              parameters:
                - in: query
                  name: mms_id
                  required: true
                  type: string
                  description: mms_id.
                - in: query
                  name: institution
                  required: false
                  type: string
                  description: institution (alma_code).
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAlmaSruRecordFunction.Arn}/invocations
                responses: {}
                httpMethod: POST
                type: AWS_PROXY
              responses:
                '200':
                  description: alma record
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/getAlmaSruRecordResponseBody'
                '400':
                  description: Bad request.
                  content:
                    application/json:
                      schema:
                        title: 400 Bad request
                        type: object
                        properties:
                          error:
                            type: string
                            description: error message
                '500':
                  description: Internal server error.
                  content:
                    application/json:
                      schema:
                        title: 500 internal server error
                        type: object
                        properties:
                          error:
                            type: string
                            description: error message

        components:
          schemas:
            getAlmaSruRecordResponseBody:
              title: alma record
              type: object
              properties:
                title:
                  type: string
                  description: bibliographic record from Alma

  GetAlmaSruRecordFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          ALMA_SRU_HOST: !Ref AlmaSruHost
          ALLOWED_ORIGIN:  '*'
      Handler: no.unit.alma.GetAlmaSruRecordHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        GetAlmaSruRecordEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref AlmaSruProxyApi
            Method: get
            Path: /

  AlmaSruProxyBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref AlmaSruProxyApi
      Stage: !Ref AlmaSruProxyApi.Stage
