name: Lint OpenAPI

permissions:
  contents: read          # To read OpenAPI files
  pull-requests: write    # To comment on PRs

on: [ push ]

jobs:
  openapi-linting:

    name: OpenAPI linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Lint OpenAPI files
        run: spectral lint 'docs/openapi.yaml' --fail-severity=error
