name: Lint OpenAPI

on: [ push ]

jobs:
  openapi-linting:

    name: OpenAPI linting
    runs-on: ubuntu-latest

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - uses: actions/checkout@v4
      - name: Validate OpenAPI definition
        uses: swaggerexpert/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: docs/openapi.yaml
